INFO:root:Model size: 48113 bytes
INFO:root:Model loaded successfully.
INFO:root:Starting main function
INFO:root:Loaded anomaly detection model successfully.
INFO:root:Analyzer initialized
INFO:root:Starting packet capture
DEBUG:asyncio:Using selector: KqueueSelector
DEBUG:root:Initiating sniffing with pyshark
DEBUG:root:Cleaning up packet capture
INFO:root:Main function execution completed
INFO:root:Model size: 48113 bytes
INFO:root:Model loaded successfully.
INFO:root:Starting main function
INFO:root:Loaded anomaly detection model successfully.
INFO:root:Analyzer initialized
INFO:root:Starting packet capture with tcpdump
INFO:root:Packet capture completed with tcpdump
DEBUG:asyncio:Using selector: KqueueSelector
INFO:root:Total packets read from file: 50
ERROR:root:An unexpected error occurred in main: [Errno 13] Permission denied: '/tmp/captured_packets.pcap'
DEBUG:root:Stack Trace: Traceback (most recent call last):
  File "/Users/apikorus/model/network_test.py", line 171, in main
    packets = analyzer.capture_packets()
              ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apikorus/model/network_test.py", line 95, in capture_packets
    os.remove(temp_file)
PermissionError: [Errno 13] Permission denied: '/tmp/captured_packets.pcap'

INFO:root:Main function execution completed
